name:                transition-graph
version:             0.1.0.0
github:              "githubuser/transition-graph"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "2018 Alexander Granin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Graph eDSL for defining nodes and transitions over an arbitrary monadic language.
# category:            Web

description:         Please see the README on Github at <https://github.com/githubuser/transition-graph#readme>

dependencies:
- base >= 4.7 && < 5
- free
- bytestring
- mtl
- transformers
- hspec
- containers
- lens
- aeson

library:
  source-dirs: src

executables:
  transition-graph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transition-graph

tests:
  transition-graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transition-graph
